-- AdGravity AI PostgreSQL Database Schema (Version 2)
-- Handles user business profiles, 7-day trials, and AI content queuing with RLS.

-- Enable UUID generation extension
create extension if not exists "uuid-ossp";

-- 1. USERS TABLE
-- Maps to Supabase auth.users but stores business information
create table public.users (
    id uuid references auth.users on delete cascade primary key,
    email text not null,
    full_name text,
    company_name text,
    category text, -- e.g. "Cafe", "Pharmacy", etc.
    meta_page_tokens jsonb default '{}'::jsonb, -- Stores Facebook/Instagram page tokens
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for users table
alter table public.users enable row level security;

-- Policies for public.users
create policy "Allow individual user select" 
    on public.users for select 
    using (auth.uid() = id);

create policy "Allow individual user update" 
    on public.users for update 
    using (auth.uid() = id);

-- 2. SUBSCRIPTIONS TABLE (7-Day Trial for ₹1 logic)
create table public.subscriptions (
    id uuid default gen_random_uuid() primary key,
    user_id uuid references public.users(id) on delete cascade unique not null,
    plan_type text not null default 'trial' check (plan_type in ('trial', 'premium', 'pro')),
    status text not null default 'trial' check (status in ('active', 'expired', 'canceled', 'trial')),
    price_paid numeric(10, 2) not null default 1.00, -- ₹1
    currency text not null default 'INR',
    trial_start timestamp with time zone default timezone('utc'::text, now()),
    trial_end timestamp with time zone default (timezone('utc'::text, now()) + interval '7 days'),
    trial_end_date timestamp with time zone default (timezone('utc'::text, now()) + interval '7 days'), -- explicit trial_end_date
    next_billing_date timestamp with time zone default (timezone('utc'::text, now()) + interval '7 days'), -- next billing date
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for subscriptions table
alter table public.subscriptions enable row level security;

-- Policies for public.subscriptions
create policy "Allow user to view their own subscription status" 
    on public.subscriptions for select 
    using (auth.uid() = user_id);

-- 3. CONTENT QUEUE TABLE (AI content, generated images, and pending admin approval list)
create table public.content_queue (
    id uuid default gen_random_uuid() primary key,
    user_id uuid references public.users(id) on delete cascade not null,
    prompt text not null,
    ai_content text, -- Text/Ad copy generated by AI
    image_url text, -- URL to generated image
    status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'published')),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for content_queue table
alter table public.content_queue enable row level security;

-- Policies for public.content_queue
create policy "Allow users to view their own queued content" 
    on public.content_queue for select 
    using (auth.uid() = user_id);

create policy "Allow users to insert their own prompt/content request" 
    on public.content_queue for insert 
    with check (auth.uid() = user_id);

create policy "Allow users to update/approve their own queued content" 
    on public.content_queue for update 
    using (auth.uid() = user_id);

create policy "Allow users to delete their own queued content" 
    on public.content_queue for delete 
    using (auth.uid() = user_id);


-- 4. PROFILE SYNCRONIZATION TRIGGER (Auth Signup Callback)
-- Automatically inserts a new row in public.users when a user signs up via Supabase Auth
create or replace function public.handle_new_user()
returns trigger as $$
begin
    insert into public.users (id, email, full_name, company_name, category)
    values (
        new.id,
        new.email,
        coalesce(new.raw_user_meta_data->>'full_name', ''),
        coalesce(new.raw_user_meta_data->>'company_name', ''),
        coalesce(new.raw_user_meta_data->>'category', '')
    );
    return new;
end;
$$ language plpgsql security definer;

-- Trigger setup
create or replace trigger on_auth_user_created
    after insert on auth.users
    for each row execute procedure public.handle_new_user();
